/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

// Register base addresses
#define RCC_BASE    0x40021000
#define GPIOC_BASE  0x40011000

// RCC - clock enable for Port C
#define RCC_APB2ENR  (*(volatile uint32_t *)(RCC_BASE + 0x18))

// GPIOC registers
#define GPIOC_CRH    (*(volatile uint32_t *)(GPIOC_BASE + 0x04))
#define GPIOC_ODR    (*(volatile uint32_t *)(GPIOC_BASE + 0x0C))

void delay(volatile uint32_t count) {
    while(count--);
}

int main(void) {
    // Step 1: Enable clock to Port C
    RCC_APB2ENR |= (1 << 4);

    // Step 2: Configure PC13 as output (CRH controls pins 8-15)
    GPIOC_CRH &= ~(0xF << 20);   // clear bits for pin 13
    GPIOC_CRH |=  (0x2 << 20);   // set as 2MHz push-pull output

    // Step 3: Blink forever
    while(1) {
        GPIOC_ODR ^= (1 << 13);  // toggle pin 13
        delay(500000);
    }
}
